In [1]:
import numpy as np

In [2]:
# ми не задумуємось якого саме типу будуть дані, пайтон сам підбирає це тип за нас
a = np.array([1,1.])
# якщо ми у масиві задани числа з плаваючою комою, тоді дані будуть типу:
a.dtype

dtype('float64')

In [3]:
# для простоих чисел, не залежно від знаку буде тип int
b = np.array([-1])
b.dtype

dtype('int32')

In [4]:
# якщо ми точно знаємо які дані у нас будуть, то можемо самостійно впливати/задавати розмірність однієї комірки
# задамо масив з найменшим значення розміру комірки
c = np.array([2, 5, 129], dtype=np.int8)
c.dtype
c
# при Int8 ми можемо оперувати числами від -127 до +127, томущо весь діапазон всього 8 біт
# розмір кожної комірки напряму впиває на Память яку займає програма

C:\Users\Admin\AppData\Local\Temp\ipykernel_14676\690972135.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  c = np.array([2, 5, 129], dtype=np.int8)


array([   2,    5, -127], dtype=int8)

In [5]:
# можемо подививтись вбудованітипи даних
np.int16

numpy.int16

In [6]:
# або можемо створювати власні типи даних для наших потреб
# для прикладу ми створимо тип даних який буде зберігати температуру з привязкою до міста
dt = np.dtype([("city", np.compat.unicode, 20), ("temperature", np.int8)])

t = np.array([("Lviv", -2), ("Odessa", 5)], dtype=dt)
# Ми можемо наприклад знайти середнє начення температур по містах
print(f"Середня температура по всіх містах: {t['temperature'].mean()} гадуси")
print(f"Всього маємо: {t['city'].shape} міст у нашому масиві")
t[1]

Середня температура по всіх містах: 1.5 гадуси
Всього маємо: (2,) міст у нашому масиві


('Odessa', 5)

In [7]:
# Дані з якими працюємо можемо зберегти у файл (не-компресований архів)

# одноразво ми згенеруємо великий масив випадкових значень та збережемо його у файл
nl = np.random.random(100000000)
# Для збереження багатьох масиві у єдинй файл ми повинні вказати ключі для цих масивів
np.savez("my_mass.npz", a=a, b=b, c=c, nl=nl)
# Ствонений файл .npz не потрібно закидати в гіт бо він буде дуже великим

In [8]:
# Звісно збережені дані можна вичитати у будь-який час
l = np.load("my_mass.npz")
# при вичитуванні, ми повинні вказати який саме з масивів ми хочемо вивести
l
print(l["c"] + 10)

[  12   15 -117]


In [9]:
np.save("my_mass.npy", nl)

In [10]:
n = np.load("my_mass.npy")
n

array([0.18038562, 0.96237239, 0.41424338, ..., 0.51937029, 0.28426165,
       0.28948803])

In [11]:
# ми можемо будь-який файл  прочитати за допомогою вбудований методів Пайтона, але чи добре ми зможемо використовувати прочитані дані
with open("1.csv") as f:
    print(f.read())
    f.seek(0)  # Дани команда переводить курсир читання у файлі на його початок
    print(f.readline())
    f.seek(0) 
    print(f.readlines())

number,date,data
1,30.11.2023,5
2,1.12.2023,17
number,date,data

['number,date,data\n', '1,30.11.2023,5\n', '2,1.12.2023,17']


In [22]:
# Для нормальної вичитування даних з CSV формату ми використаємо
nc = np.genfromtxt("1.csv", delimiter=",", dtype=(("number",np.int8), ("date",np.int8), ("data",np.int8) ), skip_header=True)
nc

TypeError: data type 'number' not understood