# Досліджуємо операції над масивами

In [1]:
import numpy as np

In [10]:
n = np.array([3, 2, 7])
s = np.array([2, 1, 3])
n ** s

array([  9,   2, 343])

In [11]:
r = np.random.random([4,5])
r

array([[0.02812422, 0.01315073, 0.75841791, 0.00773675, 0.09082522],
       [0.03355875, 0.61644252, 0.7799881 , 0.76701505, 0.39333279],
       [0.00753428, 0.99659576, 0.99610947, 0.38032191, 0.32224938],
       [0.09817561, 0.64223138, 0.94385999, 0.28637962, 0.34224867]])

In [17]:
# проблем не виникає якщо ми додаємо скаляр або одне число, 
# а якщо пробувати додати рядок до матриці ми повинні вважти щоб була збережена розмірність рядків
# тут буде виконуватись додавання по кожному з рядків окремо
a1 = r + np.array([1, 2, 3, 4, 5])
a1

array([[1.02812422, 2.01315073, 3.75841791, 4.00773675, 5.09082522],
       [1.03355875, 2.61644252, 3.7799881 , 4.76701505, 5.39333279],
       [1.00753428, 2.99659576, 3.99610947, 4.38032191, 5.32224938],
       [1.09817561, 2.64223138, 3.94385999, 4.28637962, 5.34224867]])

In [18]:
# для додавання по стовпцях ми зробили перетворення просто рядка на стовпець однак потрібно вважати 
# на розмірність (кількість елементів стовпця)
a2 = r + np.array([4,3,2,1]).reshape(4,1)
a2

array([[4.02812422, 4.01315073, 4.75841791, 4.00773675, 4.09082522],
       [3.03355875, 3.61644252, 3.7799881 , 3.76701505, 3.39333279],
       [2.00753428, 2.99659576, 2.99610947, 2.38032191, 2.32224938],
       [1.09817561, 1.64223138, 1.94385999, 1.28637962, 1.34224867]])

In [25]:
# можна робити і комплексні операції головне щоб завжди зберігались відповідні елменти до яких виконується операція
a3 = a1 ** np.array([2,3,2,3,2]) / a2
a3

array([[ 0.2624148 ,  2.03302822,  2.96857179, 16.06195388,  6.33527468],
       [ 0.35214208,  4.95281409,  3.7799881 , 28.75690968,  8.5721149 ],
       [ 0.50565778,  8.97958612,  5.32987565, 35.30875377, 12.19780215],
       [ 1.09817561, 11.23254564,  8.00162136, 61.22132761, 21.26254357]])

In [26]:
# і на останок можемо виокремити певний стовпець після пропоблених операцій
a3[:, 1]

array([ 2.03302822,  4.95281409,  8.97958612, 11.23254564])