In [1]:
# встановти бібліотеку можна також всередині Ноутбука використавши Notebook Magic, 
# це набір команд які можна викликати починаючи з симлова %
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

- чому нам потрібна дана бібліотека при роботі з числовим Python?

In [3]:
ll = list([-1, 2, 8, 9, 12, 0])
ll * 3 # Для роботи з числами це є некоректний результат, бо ми очікували просто множеня на кожен з елементів списку

[-1, 2, 8, 9, 12, 0, -1, 2, 8, 9, 12, 0, -1, 2, 8, 9, 12, 0]

In [4]:
# тут, коли ми хочемо зробити додавання до кожного з елементів взагалі буде помилка
#ll + 2
# також помилка коли ми хочемо поділити список з чисел на якесь число
#ll / 2

In [5]:
# Для роботи поелементно на потрібно використовувати цикли
lf = [i * 3 for i in ll]
lf

[-3, 6, 24, 27, 36, 0]

In [6]:
# Можна робоити і складніші математичні операції, одак тільки поелементно
lf = [i / 2 + 4 for i in ll]
lf

[3.5, 5.0, 8.0, 8.5, 10.0, 4.0]

In [7]:
from random import randint

# Наступні 2 комірки будуть тормозити компютер тому що генерація 100 мільйонів чисел це досить багато даних
#ll = list([randint(-5, 5) for _ in range(100000000)])
# це генерувалось 51 секунду

In [8]:
# цей масив буде ще більшим томущо ділення нам переведе цілочисельний тип int в з плаваючою крапкою float
#lf = [i / 2 + 4 for i in ll]
#lf[0:10]
# Це операція виконувалась аж 10 секунд!

- для роботи з дуже великим набором даних, використовувати базові методи Python стає неоптимально (довгий час виконання та займає бугуто оперативної памяті)

In [9]:
nl = np.random.random(100000000)
nl[0:10]
# тут такий жеж великий обсяг даних ми гненерували менше ніж за секунду!

array([0.94762084, 0.65046047, 0.76373057, 0.1142594 , 0.50007933,
       0.97004444, 0.519723  , 0.8441755 , 0.99668879, 0.00235901])

In [10]:
# використовуючи бібліотеку numpy ми можемо працювати з числами швидко та у зрозумілому для нас форматі
# і щоб операції були виконані над всіма елементами масиву нам не потрібні цикли!
nf = nl / 2 + 4
nf[0:10]

array([4.47381042, 4.32523024, 4.38186528, 4.0571297 , 4.25003967,
       4.48502222, 4.2598615 , 4.42208775, 4.49834439, 4.0011795 ])

In [11]:
# У Пайтон набір даних це є список (list)
# При використання бібліотеки numpy - набір даних буде називатись масив (array)
ll = ["4", 4, 9]
na = np.array(ll,dtype=int)
na

array([4, 4, 9])

In [12]:
(na + 12) / 8 

array([2.   , 2.   , 2.625])

In [13]:
# вектор рядок
a = np.array([1, 2, 6, 10]) # дані в рядок / горизонтальні
a*5 - 4

array([ 1,  6, 26, 46])

In [14]:
# і може бути вектор стовпець
b = np.array([[1], [2], [6]]) # просто дані тепер розміщуються вертикально
b*5 - 4

array([[ 1],
       [ 6],
       [26]])

In [15]:
print(f"Вектор стрічка буде мати форму: {a.shape}\nА вектор стовпець буде мати форму: {b.shape}")
print(f"Для вектор рядка має кількість вимірів: {a.ndim}\nА для вектор стовпця вже буде: {b.ndim}")

Вектор стрічка буде мати форму: (4,)
А вектор стовпець буде мати форму: (3, 1)
Для вектор рядка має кількість вимірів: 1
А для вектор стовпця вже буде: 2


- методи створення numpy масиві з заданою послідовністю чисел
> задана послідовність - це числа з кроком, або набір по наростанню або спаданню
> може ще бути випадковий набір чисел, але це відноситься до бібліотек random

In [32]:
# послідовні дані можна згенерувати вбудованою функцією range, але це не спосіб роботи з numpy
# по замовчуванню, числа генеруються від 0
# крок генерації по замовчуванню буде 1
x = np.arange(5, 50, 0.2)
# тут буде в основному згенеровано вектор рядки / стрічки / горизонтальні набір даних

x

array([ 5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,
        7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,
        9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4,
       11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6,
       13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8,
       16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4, 17.6, 17.8, 18. ,
       18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6, 19.8, 20. , 20.2,
       20.4, 20.6, 20.8, 21. , 21.2, 21.4, 21.6, 21.8, 22. , 22.2, 22.4,
       22.6, 22.8, 23. , 23.2, 23.4, 23.6, 23.8, 24. , 24.2, 24.4, 24.6,
       24.8, 25. , 25.2, 25.4, 25.6, 25.8, 26. , 26.2, 26.4, 26.6, 26.8,
       27. , 27.2, 27.4, 27.6, 27.8, 28. , 28.2, 28.4, 28.6, 28.8, 29. ,
       29.2, 29.4, 29.6, 29.8, 30. , 30.2, 30.4, 30.6, 30.8, 31. , 31.2,
       31.4, 31.6, 31.8, 32. , 32.2, 32.4, 32.6, 32.8, 33. , 33.2, 33.4,
       33.6, 33.8, 34. , 34.2, 34.4, 34.6, 34.8, 35

In [34]:
# і далі ми можемо робити з даним вектором будь-які арифметичні операції
x * 3 + x / 2

array([ 17.5,  18.2,  18.9,  19.6,  20.3,  21. ,  21.7,  22.4,  23.1,
        23.8,  24.5,  25.2,  25.9,  26.6,  27.3,  28. ,  28.7,  29.4,
        30.1,  30.8,  31.5,  32.2,  32.9,  33.6,  34.3,  35. ,  35.7,
        36.4,  37.1,  37.8,  38.5,  39.2,  39.9,  40.6,  41.3,  42. ,
        42.7,  43.4,  44.1,  44.8,  45.5,  46.2,  46.9,  47.6,  48.3,
        49. ,  49.7,  50.4,  51.1,  51.8,  52.5,  53.2,  53.9,  54.6,
        55.3,  56. ,  56.7,  57.4,  58.1,  58.8,  59.5,  60.2,  60.9,
        61.6,  62.3,  63. ,  63.7,  64.4,  65.1,  65.8,  66.5,  67.2,
        67.9,  68.6,  69.3,  70. ,  70.7,  71.4,  72.1,  72.8,  73.5,
        74.2,  74.9,  75.6,  76.3,  77. ,  77.7,  78.4,  79.1,  79.8,
        80.5,  81.2,  81.9,  82.6,  83.3,  84. ,  84.7,  85.4,  86.1,
        86.8,  87.5,  88.2,  88.9,  89.6,  90.3,  91. ,  91.7,  92.4,
        93.1,  93.8,  94.5,  95.2,  95.9,  96.6,  97.3,  98. ,  98.7,
        99.4, 100.1, 100.8, 101.5, 102.2, 102.9, 103.6, 104.3, 105. ,
       105.7, 106.4,

In [22]:
# Використовуючи методи слайсінгу які притаманні спискам ми також можемо виділити певну множину чисел з нашого початкового масиву
x[0] # в будь-якому масиві номерація йду з нуля
x[-1] # Це буде останній елемент тому що номерація з кінця
x[0:10] # беремо слайс (набір елементів) не включаючи останнього

array([5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8])

In [29]:
y = np.arange(225)
y[3:6]

array([3, 4, 5])

In [31]:
x[4:10] + y[3:9]

array([ 8.8, 10. , 11.2, 12.4, 13.6, 14.8])

In [36]:
# оскільки в нас вже є сортовані масиви, то напростіше в слайсінгу є те що ми хочемо взяти граничні значення
# наприклад 10 з найбільшим чи найменшим значенням
u = x * 3 + y / 3 
u[:10] # упускаю початкове значення бо беремо перші 10

array([15.        , 15.93333333, 16.86666667, 17.8       , 18.73333333,
       19.66666667, 20.6       , 21.53333333, 22.46666667, 23.4       ])