In [1]:
# встановти бібліотеку можна також всередині Ноутбука використавши Notebook Magic, 
# це набір команд які можна викликати починаючи з симлова %
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

- чому нам потрібна дана бібліотека при роботі з числовим Python?

In [3]:
ll = list([-1, 2, 8, 9, 12, 0])
ll * 3 # Для роботи з числами це є некоректний результат, бо ми очікували просто множеня на кожен з елементів списку

[-1, 2, 8, 9, 12, 0, -1, 2, 8, 9, 12, 0, -1, 2, 8, 9, 12, 0]

In [4]:
# тут, коли ми хочемо зробити додавання до кожного з елементів взагалі буде помилка
#ll + 2
# також помилка коли ми хочемо поділити список з чисел на якесь число
#ll / 2

In [5]:
# Для роботи поелементно на потрібно використовувати цикли
lf = [i * 3 for i in ll]
lf

[-3, 6, 24, 27, 36, 0]

In [6]:
# Можна робоити і складніші математичні операції, одак тільки поелементно
lf = [i / 2 + 4 for i in ll]
lf

[3.5, 5.0, 8.0, 8.5, 10.0, 4.0]

In [7]:
from random import randint

# Наступні 2 комірки будуть тормозити компютер тому що генерація 100 мільйонів чисел це досить багато даних
#ll = list([randint(-5, 5) for _ in range(100000000)])
# це генерувалось 51 секунду

In [8]:
# цей масив буде ще більшим томущо ділення нам переведе цілочисельний тип int в з плаваючою крапкою float
#lf = [i / 2 + 4 for i in ll]
#lf[0:10]
# Це операція виконувалась аж 10 секунд!

- для роботи з дуже великим набором даних, використовувати базові методи Python стає неоптимально (довгий час виконання та займає бугуто оперативної памяті)

In [9]:
nl = np.random.random(100000000)
nl[0:10]
# тут такий жеж великий обсяг даних ми гненерували менше ніж за секунду!

array([0.7155764 , 0.82784054, 0.64024582, 0.93760271, 0.51246423,
       0.91158222, 0.3553986 , 0.87515908, 0.1091382 , 0.67154996])

In [10]:
# використовуючи бібліотеку numpy ми можемо працювати з числами швидко та у зрозумілому для нас форматі
# і щоб операції були виконані над всіма елементами масиву нам не потрібні цикли!
nf = nl / 2 + 4
nf[0:10]

array([4.3577882 , 4.41392027, 4.32012291, 4.46880136, 4.25623211,
       4.45579111, 4.1776993 , 4.43757954, 4.0545691 , 4.33577498])

In [22]:
# У Пайтон набір даних це є список (list)
# При використання бібліотеки numpy - набір даних буде називатись масив (array)
ll = ["4", 4, 9]
na = np.array(ll,dtype=int)
na

array([4, 4, 9])

In [19]:
(na + 12) / 8 

array([1.75 , 2.   , 2.625])

In [28]:
# вектор рядок
a = np.array([1, 2, 6, 10]) # дані в рядок / горизонтальні
a*5 - 4

array([ 1,  6, 26, 46])

In [26]:
# і може бути вектор стовпець
b = np.array([[1], [2], [6]]) # просто дані тепер розміщуються вертикально
b*5 - 4

array([[ 1],
       [ 6],
       [26]])

In [36]:
print(f"Вектор стрічка буде мати форму: {a.shape}\nА вектор стовпець буде мати форму: {b.shape}")
print(f"Для вектор рядка має кількість вимірів: {a.ndim}\nА для вектор стовпця вже буде: {b.ndim}")

Вектор стрічка буде мати форму: (4,)
А вектор стовпець буде мати форму: (3, 1)
Для вектор рядка має кількість вимірів: 1
А для вектор стовпця вже буде: 2


- методи створення numpy масиві з заданою послідовністю чисел
> задана послідовність - це числа з кроком, або набір по наростанню або спаданню
> може ще бути випадковий набір чисел, але це відноситься до бібліотек random

In [44]:
# послідовні дані можна згенерувати вбудованою функцією range, але це не спосіб роботи з numpy
# по замовчуванню, числа генеруються від 0
# крок генерації по замовчуванню буде 1
np.arange(5, 50, 0.2).shape
# тут буде в основному згенеровано вектор рядки / стрічки / горизонтальні набір даних

1